### ISSUE TITLE
Address "Invalid TIFF file" SCIFIO errors

### ISSUE THREAD

**Issue by ctrueden** [scijava/pom-scijava#121]
The latest versions of SCIFIO have problems with some components. Updating these components to pom-scijava 29.0.0-beta-1 and attempting to build fails with `io.scif.FormatException: Invalid TIFF file`.

Known problems include:

<details><summary>imagej-opencv</summary>

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running net.imagej.opencv.IntImageConvertersTest
log4j:WARN No appenders could be found for logger (org.bushe.swing.event.EventService).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 1.748 s <<< FAILURE! - in net.imagej.opencv.IntImageConvertersTest
[ERROR] testImgToMatConversion(net.imagej.opencv.IntImageConvertersTest)  Time elapsed: 0.028 s  <<< ERROR!
java.io.IOException: io.scif.img.ImgIOException: java.io.IOException: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.IntImageConvertersTest.testImgToMatConversion(IntImageConvertersTest.java:47)
Caused by: io.scif.img.ImgIOException: java.io.IOException: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.IntImageConvertersTest.testImgToMatConversion(IntImageConvertersTest.java:47)
Caused by: java.io.IOException: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.IntImageConvertersTest.testImgToMatConversion(IntImageConvertersTest.java:47)
Caused by: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.IntImageConvertersTest.testImgToMatConversion(IntImageConvertersTest.java:47)

[ERROR] testFullCircleConversionFromIJ(net.imagej.opencv.IntImageConvertersTest)  Time elapsed: 0 s  <<< ERROR!
java.io.IOException: io.scif.img.ImgIOException: java.io.IOException: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.IntImageConvertersTest.testFullCircleConversionFromIJ(IntImageConvertersTest.java:59)
Caused by: io.scif.img.ImgIOException: java.io.IOException: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.IntImageConvertersTest.testFullCircleConversionFromIJ(IntImageConvertersTest.java:59)
Caused by: java.io.IOException: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.IntImageConvertersTest.testFullCircleConversionFromIJ(IntImageConvertersTest.java:59)
Caused by: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.IntImageConvertersTest.testFullCircleConversionFromIJ(IntImageConvertersTest.java:59)

[INFO] Running net.imagej.opencv.StackedImageTest
[ERROR] Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 1.856 s <<< FAILURE! - in net.imagej.opencv.StackedImageTest
[ERROR] testFullCircleConversionFromMatVector(net.imagej.opencv.StackedImageTest)  Time elapsed: 1.44 s  <<< ERROR!
java.io.IOException: Couldn't load image: /Users/curtis/code/imagej/imagej-opencv/test/input.tif
	at net.imagej.opencv.StackedImageTest.testFullCircleConversionFromMatVector(StackedImageTest.java:67)

[ERROR] testImgToMatVectorConversion(net.imagej.opencv.StackedImageTest)  Time elapsed: 0.247 s  <<< ERROR!
java.io.IOException: io.scif.img.ImgIOException: java.io.IOException: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.StackedImageTest.testImgToMatVectorConversion(StackedImageTest.java:100)
Caused by: io.scif.img.ImgIOException: java.io.IOException: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.StackedImageTest.testImgToMatVectorConversion(StackedImageTest.java:100)
Caused by: java.io.IOException: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.StackedImageTest.testImgToMatVectorConversion(StackedImageTest.java:100)
Caused by: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.StackedImageTest.testImgToMatVectorConversion(StackedImageTest.java:100)

[ERROR] testMatVectorToImgComversion(net.imagej.opencv.StackedImageTest)  Time elapsed: 0 s  <<< ERROR!
java.io.IOException: Couldn't load image: /Users/curtis/code/imagej/imagej-opencv/test/input.tif
	at net.imagej.opencv.StackedImageTest.testMatVectorToImgComversion(StackedImageTest.java:85)

[ERROR] testFullCircleConversionFromIJ(net.imagej.opencv.StackedImageTest)  Time elapsed: 0.061 s  <<< ERROR!
java.io.IOException: io.scif.img.ImgIOException: java.io.IOException: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.StackedImageTest.testFullCircleConversionFromIJ(StackedImageTest.java:46)
Caused by: io.scif.img.ImgIOException: java.io.IOException: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.StackedImageTest.testFullCircleConversionFromIJ(StackedImageTest.java:46)
Caused by: java.io.IOException: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.StackedImageTest.testFullCircleConversionFromIJ(StackedImageTest.java:46)
Caused by: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.StackedImageTest.testFullCircleConversionFromIJ(StackedImageTest.java:46)

[INFO] Running net.imagej.opencv.DoubleImageConvertersTest
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.134 s <<< FAILURE! - in net.imagej.opencv.DoubleImageConvertersTest
[ERROR] testImgToMatConversion(net.imagej.opencv.DoubleImageConvertersTest)  Time elapsed: 0.003 s  <<< ERROR!
java.io.IOException: io.scif.img.ImgIOException: java.io.IOException: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.DoubleImageConvertersTest.testImgToMatConversion(DoubleImageConvertersTest.java:47)
Caused by: io.scif.img.ImgIOException: java.io.IOException: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.DoubleImageConvertersTest.testImgToMatConversion(DoubleImageConvertersTest.java:47)
Caused by: java.io.IOException: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.DoubleImageConvertersTest.testImgToMatConversion(DoubleImageConvertersTest.java:47)
Caused by: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.DoubleImageConvertersTest.testImgToMatConversion(DoubleImageConvertersTest.java:47)

[ERROR] testFullCircleConversionFromIJ(net.imagej.opencv.DoubleImageConvertersTest)  Time elapsed: 0.001 s  <<< ERROR!
java.io.IOException: io.scif.img.ImgIOException: java.io.IOException: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.DoubleImageConvertersTest.testFullCircleConversionFromIJ(DoubleImageConvertersTest.java:59)
Caused by: io.scif.img.ImgIOException: java.io.IOException: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.DoubleImageConvertersTest.testFullCircleConversionFromIJ(DoubleImageConvertersTest.java:59)
Caused by: java.io.IOException: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.DoubleImageConvertersTest.testFullCircleConversionFromIJ(DoubleImageConvertersTest.java:59)
Caused by: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.DoubleImageConvertersTest.testFullCircleConversionFromIJ(DoubleImageConvertersTest.java:59)

[INFO] Running net.imagej.opencv.ByteImageConvertersTest
[ERROR] Tests run: 5, Failures: 3, Errors: 2, Skipped: 0, Time elapsed: 0.449 s <<< FAILURE! - in net.imagej.opencv.ByteImageConvertersTest
[ERROR] testFullCircleConversionFromMat(net.imagej.opencv.ByteImageConvertersTest)  Time elapsed: 0.419 s  <<< FAILURE!
java.lang.AssertionError: Couldn't load image: /Users/curtis/code/imagej/imagej-opencv/test/input.tif
	at net.imagej.opencv.ByteImageConvertersTest.testFullCircleConversionFromMat(ByteImageConvertersTest.java:95)

[ERROR] testMatToImgConversion(net.imagej.opencv.ByteImageConvertersTest)  Time elapsed: 0.001 s  <<< FAILURE!
java.lang.AssertionError: Couldn't load image: /Users/curtis/code/imagej/imagej-opencv/test/input.tif
	at net.imagej.opencv.ByteImageConvertersTest.testMatToImgConversion(ByteImageConvertersTest.java:59)

[ERROR] testImgToMatConversion(net.imagej.opencv.ByteImageConvertersTest)  Time elapsed: 0.003 s  <<< ERROR!
java.io.IOException: io.scif.img.ImgIOException: java.io.IOException: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.ByteImageConvertersTest.testImgToMatConversion(ByteImageConvertersTest.java:76)
Caused by: io.scif.img.ImgIOException: java.io.IOException: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.ByteImageConvertersTest.testImgToMatConversion(ByteImageConvertersTest.java:76)
Caused by: java.io.IOException: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.ByteImageConvertersTest.testImgToMatConversion(ByteImageConvertersTest.java:76)
Caused by: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.ByteImageConvertersTest.testImgToMatConversion(ByteImageConvertersTest.java:76)

[ERROR] testMatAndImgArraysAreSameShape(net.imagej.opencv.ByteImageConvertersTest)  Time elapsed: 0 s  <<< FAILURE!
java.lang.AssertionError: Couldn't load image: /Users/curtis/code/imagej/imagej-opencv/test/input.tif
	at net.imagej.opencv.ByteImageConvertersTest.testMatAndImgArraysAreSameShape(ByteImageConvertersTest.java:44)

[ERROR] testFullCircleConversionFromIJ(net.imagej.opencv.ByteImageConvertersTest)  Time elapsed: 0.001 s  <<< ERROR!
java.io.IOException: io.scif.img.ImgIOException: java.io.IOException: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.ByteImageConvertersTest.testFullCircleConversionFromIJ(ByteImageConvertersTest.java:107)
Caused by: io.scif.img.ImgIOException: java.io.IOException: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.ByteImageConvertersTest.testFullCircleConversionFromIJ(ByteImageConvertersTest.java:107)
Caused by: java.io.IOException: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.ByteImageConvertersTest.testFullCircleConversionFromIJ(ByteImageConvertersTest.java:107)
Caused by: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.ByteImageConvertersTest.testFullCircleConversionFromIJ(ByteImageConvertersTest.java:107)

[INFO] Running net.imagej.opencv.FloatImageConvertersTest
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.001 s <<< FAILURE! - in net.imagej.opencv.FloatImageConvertersTest
[ERROR] testImgToMatConversion(net.imagej.opencv.FloatImageConvertersTest)  Time elapsed: 0 s  <<< ERROR!
java.io.IOException: io.scif.img.ImgIOException: java.io.IOException: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.FloatImageConvertersTest.testImgToMatConversion(FloatImageConvertersTest.java:47)
Caused by: io.scif.img.ImgIOException: java.io.IOException: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.FloatImageConvertersTest.testImgToMatConversion(FloatImageConvertersTest.java:47)
Caused by: java.io.IOException: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.FloatImageConvertersTest.testImgToMatConversion(FloatImageConvertersTest.java:47)
Caused by: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.FloatImageConvertersTest.testImgToMatConversion(FloatImageConvertersTest.java:47)

[ERROR] testFullCircleConversionFromIJ(net.imagej.opencv.FloatImageConvertersTest)  Time elapsed: 0.001 s  <<< ERROR!
java.io.IOException: io.scif.img.ImgIOException: java.io.IOException: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.FloatImageConvertersTest.testFullCircleConversionFromIJ(FloatImageConvertersTest.java:59)
Caused by: io.scif.img.ImgIOException: java.io.IOException: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.FloatImageConvertersTest.testFullCircleConversionFromIJ(FloatImageConvertersTest.java:59)
Caused by: java.io.IOException: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.FloatImageConvertersTest.testFullCircleConversionFromIJ(FloatImageConvertersTest.java:59)
Caused by: io.scif.FormatException: Invalid TIFF file
	at net.imagej.opencv.FloatImageConvertersTest.testFullCircleConversionFromIJ(FloatImageConvertersTest.java:59)

[INFO] Running net.imagej.opencv.RealStackedImageTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.806 s - in net.imagej.opencv.RealStackedImageTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   ByteImageConvertersTest.testFullCircleConversionFromMat:95 Couldn't load image: /Users/curtis/code/imagej/imagej-opencv/test/input.tif
[ERROR]   ByteImageConvertersTest.testMatAndImgArraysAreSameShape:44 Couldn't load image: /Users/curtis/code/imagej/imagej-opencv/test/input.tif
[ERROR]   ByteImageConvertersTest.testMatToImgConversion:59 Couldn't load image: /Users/curtis/code/imagej/imagej-opencv/test/input.tif
[ERROR] Errors:
[ERROR]   ByteImageConvertersTest.testFullCircleConversionFromIJ:107 » IO io.scif.img.Im...
[ERROR]   ByteImageConvertersTest.testImgToMatConversion:76 » IO io.scif.img.ImgIOExcept...
[ERROR]   DoubleImageConvertersTest.testFullCircleConversionFromIJ:59 » IO io.scif.img.I...
[ERROR]   DoubleImageConvertersTest.testImgToMatConversion:47 » IO io.scif.img.ImgIOExce...
[ERROR]   FloatImageConvertersTest.testFullCircleConversionFromIJ:59 » IO io.scif.img.Im...
[ERROR]   FloatImageConvertersTest.testImgToMatConversion:47 » IO io.scif.img.ImgIOExcep...
[ERROR]   IntImageConvertersTest.testFullCircleConversionFromIJ:59 » IO io.scif.img.ImgI...
[ERROR]   IntImageConvertersTest.testImgToMatConversion:47 » IO io.scif.img.ImgIOExcepti...
[ERROR]   StackedImageTest.testFullCircleConversionFromIJ:46 » IO io.scif.img.ImgIOExcep...
[ERROR]   StackedImageTest.testFullCircleConversionFromMatVector:67 IO Couldn't load ima...
[ERROR]   StackedImageTest.testImgToMatVectorConversion:100 » IO io.scif.img.ImgIOExcept...
[ERROR]   StackedImageTest.testMatVectorToImgComversion:85 IO Couldn't load image: /User...
[INFO]
[ERROR] Tests run: 20, Failures: 3, Errors: 12, Skipped: 0
```

</details>

<details><summary>imagej-scripting</summary>

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running net.imagej.scripting.ImageJ2ScriptTest
log4j:WARN No appenders could be found for logger (org.bushe.swing.event.EventService).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[ERROR] Traceback (most recent call last):
  File "/Users/curtis/code/imagej/imagej-scripting/target/classes/script_templates/ImageJ2/Stack_Directory_Images.py", line 31, in <module>
    data = io.open(fname)
	at io.scif.services.DefaultDatasetIOService.open(DefaultDatasetIOService.java:163)
	at io.scif.services.DefaultDatasetIOService.open(DefaultDatasetIOService.java:133)
	at io.scif.services.DefaultDatasetIOService.open(DefaultDatasetIOService.java:138)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
java.io.IOException: java.io.IOException: io.scif.img.ImgIOException: java.io.IOException: io.scif.FormatException: Invalid TIFF file

	at org.python.core.Py.JavaError(Py.java:547)
	at org.python.core.Py.JavaError(Py.java:538)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:192)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:208)
	at org.python.core.PyObject.__call__(PyObject.java:477)
	at org.python.core.PyObject.__call__(PyObject.java:481)
	at org.python.core.PyMethod.__call__(PyMethod.java:141)
	at org.python.pycode._pyx1.f$0(/Users/curtis/code/imagej/imagej-scripting/target/classes/script_templates/ImageJ2/Stack_Directory_Images.py:44)
	at org.python.pycode._pyx1.call_function(/Users/curtis/code/imagej/imagej-scripting/target/classes/script_templates/ImageJ2/Stack_Directory_Images.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1687)
	at org.python.core.__builtin__.eval(__builtin__.java:497)
	at org.python.core.__builtin__.eval(__builtin__.java:501)
	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:255)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:57)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:157)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: io.scif.img.ImgIOException: java.io.IOException: io.scif.FormatException: Invalid TIFF file
	at io.scif.services.DefaultDatasetIOService.open(DefaultDatasetIOService.java:163)
	at io.scif.services.DefaultDatasetIOService.open(DefaultDatasetIOService.java:133)
	at io.scif.services.DefaultDatasetIOService.open(DefaultDatasetIOService.java:138)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:190)
	... 24 more
Caused by: io.scif.img.ImgIOException: java.io.IOException: io.scif.FormatException: Invalid TIFF file
	at io.scif.img.ImgOpener.createReader(ImgOpener.java:489)
	at io.scif.img.ImgOpener.openImgs(ImgOpener.java:242)
	at io.scif.services.DefaultDatasetIOService.open(DefaultDatasetIOService.java:152)
	... 31 more
Caused by: java.io.IOException: io.scif.FormatException: Invalid TIFF file
	at io.scif.AbstractReader.setSource(AbstractReader.java:279)
	at io.scif.services.DefaultInitializeService.initializeReader(DefaultInitializeService.java:91)
	at io.scif.img.ImgOpener.createReader(ImgOpener.java:483)
	... 33 more
Caused by: io.scif.FormatException: Invalid TIFF file
	at io.scif.formats.MinimalTIFFFormat$Parser.typedParse(MinimalTIFFFormat.java:412)
	at io.scif.formats.TIFFFormat$BaseTIFFParser.typedParse(TIFFFormat.java:957)
	at io.scif.formats.TIFFFormat$BaseTIFFParser.typedParse(TIFFFormat.java:939)
	at io.scif.AbstractParser.parse(AbstractParser.java:244)
	at io.scif.AbstractParser.parse(AbstractParser.java:314)
	at io.scif.AbstractParser.parse(AbstractParser.java:53)
	at io.scif.AbstractReader.setSource(AbstractReader.java:271)
	... 35 more
[ERROR] Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 11.604 s <<< FAILURE! - in net.imagej.scripting.ImageJ2ScriptTest
[ERROR] testStackDirectoryImagesScript(net.imagej.scripting.ImageJ2ScriptTest)  Time elapsed: 0.528 s  <<< ERROR!
java.lang.NullPointerException
	at net.imagej.scripting.ImageJ2ScriptTest.testStackDirectoryImagesScript(ImageJ2ScriptTest.java:225)

[INFO] Running net.imagej.scripting.TutorialsScriptTest
[100L, 100L]
axis 0: type: X length: 100
axis 1: type: Y length: 100
axis 2: type: Z length: 100
ConvolveFFTC: fftInput = ArrayImg [61x120], fftKernel = ArrayImg [61x120]
size 212 intensity -6.21226415094
size 8971 intensity -74.9077025973
ConvolveFFTC: fftInput = ArrayImg [81x168x60], fftKernel = ArrayImg [81x168x60]
[WARNING] Unmatched input: sigma2
[WARNING] Unmatched input: sigma1
axis d: type: X length: 400
axis d: type: Y length: 400
axis d: type: Channel length: 2
axis d: type: Z length: 25
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.161 s - in net.imagej.scripting.TutorialsScriptTest
[INFO] Running net.imagej.scripting.DeconvolutionScriptTest
[INFO] null = ArrayImg [13x13x37]
ConvolveFFTC: fftInput = ArrayImg [61x120x90], fftKernel = ArrayImg [61x120x90]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 13.25 s - in net.imagej.scripting.DeconvolutionScriptTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   ImageJ2ScriptTest.testStackDirectoryImagesScript:225->AbstractScriptTest.assertConstant:103 » NullPointer
[INFO]
[ERROR] Tests run: 15, Failures: 0, Errors: 1, Skipped: 0
```

</details>

**Comment by hinerm** [comment]
@ctrueden both of these now build successfully with `29.0.0-beta-2` and [the latest scifio](https://github.com/scifio/scifio/commit/902c740fb17972c69e542c1d21953a75c1ed433d).
