### ISSUE TITLE
Update OMEVisual to work with the new SCIFIO

### ISSUE THREAD

**Issue by ctrueden** [scijava/pom-scijava#123]
```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/curtis/code/fiji-ext/OMEVisual/src/main/java/sc/fiji/omevisual/OMEUtils.java:[17,27] package io.scif.ome.formats does not exist
[INFO] 1 error
[INFO] -------------------------------------------------------------
```

There is no SCIFIO `OMETIFFFormat` anymore. We rely on `scifio-bf-compat` for that. Probably, OMEVisual needs to grab the original format-specific `Metadata` object from the SCIFIO-opened image, and then translate it to an `OMEMetadata`, which it can display.

**Comment by hinerm** [comment]
I [updated OMEVisual](https://github.com/hinerm/OMEVisual/tree/sjc-29) to translate, which seems reasonable in theory. I am working on testing to confirm but unfortunately with pom-scijava 29 something breaks in OMEVisual's test class. When it launches the legacy UI I get
```
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686)
	at java.util.zip.ZipFile.getInputStream(ZipFile.java:366)
	at java.util.jar.JarFile.getInputStream(JarFile.java:452)
	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:164)
	at sun.awt.image.URLImageSource.getDecoder(URLImageSource.java:127)
	at sun.awt.image.InputStreamImageSource.doFetch(InputStreamImageSource.java:263)
	at sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:205)
	at sun.awt.image.ImageFetcher.run(ImageFetcher.java:169)
```

So... still investigating

**Comment by frauzufall** [comment]
@hinerm https://github.com/imagej/imagej-legacy/pull/245 might be helpful

**Comment by hinerm** [comment]
@frauzufall yep that totally fixes it.
